version: '3'
services:
  teamcity-server:
    image: jetbrains/teamcity-server
    container_name: teamcity-server
    volumes:
      - ./teamcity/data:/data/teamcity_server/datadir
      - ./teamcity/logs:/opt/teamcity/logs
    ports:
      - "8111:8111"
    restart: unless-stopped

  teamcity-agent:
    image: jetbrains/teamcity-agent
    container_name: teamcity-agent
    environment:
      - SERVER_URL=http://teamcity-server:8111
    volumes:
      - ./teamcity/agent/conf:/data/teamcity_agent/conf
    depends_on:
      - teamcity-server
    restart: unless-stopped
